# Generated by Django 5.2.5 on 2025-08-27 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('user', 'chat_room')},
        ),
    ]
